apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditrack-api
  namespace: meditrack-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meditrack-api
  template:
    metadata:
      labels:
        app: meditrack-api
    spec:
      containers:
      - name: meditrack-api
        image: acrdevopsfinalas2.azurecr.io/meditrack-api:v1
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet: { path: /health, port: 3000 }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 3000 }
          initialDelaySeconds: 10
          periodSeconds: 15
