name: MediTrack CI/CD (local)

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v4
      - name: Construir imagen
        run: docker build -t meditrack-api:local api/
      - name: Cargar imagen a minikube
        run: minikube image load meditrack-api:local

  deploy-dev:
    needs: ci
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v4
      - run: kubectl apply -k k8s/overlays/dev

  deploy-qa:
    needs: deploy-dev
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v4
      - run: kubectl apply -k k8s/overlays/qa

  deploy-prod:
    needs: deploy-qa
    runs-on: [self-hosted, dev]
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - run: kubectl apply -k k8s/overlays/prod
      - run: kubectl rollout restart deployment/meditrack-api -n meditrack-prod
      - run: kubectl rollout status deployment/meditrack-api -n meditrack-prod --timeout=210s
      - name: Rollback si falla
        if: failure()
        run: kubectl rollout undo deployment/meditrack-api -n meditrack-prod
