name: MediTrack CI/CD (local)
on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v4
      - name: Deps + Jest
        working-directory: api
        run: |
          npm ci
          npm test
      - name: Construir imagen
        run: docker build -t meditrack-api:local api/
      - name: Trivy (reporta, no bloquea)
        run: trivy image --exit-code 0 --severity CRITICAL,HIGH meditrack-api:local
      - name: Cargar imagen en minikube
        run: minikube image load meditrack-api:local

  deploy-dev:
    needs: ci
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v4
      - run: |
          kubectl apply -k k8s/overlays/dev
          kubectl rollout restart deployment/meditrack-api -n meditrack-dev
          kubectl rollout status deployment/meditrack-api -n meditrack-dev --timeout=90s

  deploy-qa:
    needs: deploy-dev
    runs-on: [self-hosted, qa]
    steps:
      - uses: actions/checkout@v4
      - run: |
          kubectl apply -k k8s/overlays/qa
          kubectl rollout restart deployment/meditrack-api -n meditrack-qa
          kubectl rollout status deployment/meditrack-api -n meditrack-qa --timeout=90s

  deploy-prod:
    needs: deploy-qa
    runs-on: [self-hosted, prod]
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - run: |
          kubectl apply -k k8s/overlays/prod
          kubectl rollout restart deployment/meditrack-api -n meditrack-prod
          kubectl rollout status deployment/meditrack-api -n meditrack-prod --timeout=90s
      - name: Rollback si falla
        if: failure()
        run: kubectl rollout undo deployment/meditrack-api -n meditrack-prod
